### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by nicu-chiciuc** [Fabianopb/express-react-ts-ci#1]
As the title says, on `yarn install` I'm getting the following error. At the moment I'm trying to figure out if there's a problem with the versioning of the any of the packages.
```
error /Users/nicusor/Dev/GITOTHER/express-react-ts-ci/backend/node_modules/mongodb-memory-server: Command failed.
Exit code: 1
Command: node ./postinstall.js
Arguments:
Directory: /Users/nicusor/Dev/GITOTHER/express-react-ts-ci/backend/node_modules/mongodb-memory-server
Output:
mongodb-memory-server: checking MongoDB binaries cache...
Downloading: https://fastdl.mongodb.org/osx/mongodb-osx-ssl-x86_64-latest.tgz
events.js:180ongoDB latest: 99 % (66.3mb / 66.9mb)b)
    throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'listener', 'Function');
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type Function
    at _addListener (events.js:180:11)
    at WriteStream.addListener (events.js:240:10)
    at WriteStream.close (fs.js:2302:10)
    at WriteStream.<anonymous> (/Users/nicusor/Dev/GITOTHER/express-react-ts-ci/backend/node_modules/mongodb-memory-server/lib/util/MongoBinaryDownload.js:217:24)
    at WriteStream.emit (events.js:164:20)
    at finishMaybe (_stream_writable.js:605:14)
    at afterWrite (_stream_writable.js:456:3)
```

**Comment by nicu-chiciuc** [comment]
Ok, the problem was I was using node 9.x. I've switched to 8 and everything seems to to install correctly.

**Comment by Fabianopb** [comment]
Hi @nicu-chiciuc, thanks for the heads up and sorry for the delay to answer, for some reason I didn't get an email notification about this.

Thanks for pointing that out, the information is somewhat hidden in `package.json`:
```json
"engines": {
  "node": "8.x",
  "yarn": "1.x"
}
```

So you're right, this information should be more clear or then allow node > 8 in the engine! I'll open a new issue to take care of this!
